# Generated by Django 3.0.3 on 2020-02-19 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authors_app', '0002_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Books',
        ),
    ]
